const express=require('express'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const app=express(),PORT=Number(process.env.PORT||3000),ADMIN_KEY=process.env.ADMIN_KEY||'',ALLOWED_HOST=process.env.ALLOWED_HOST||'';
const DATA=path.join(__dirname,'customers.json');
app.use(express.json({limit:'20kb'})); app.use(express.static(path.join(__dirname,'public')));
const load=()=>{try{return JSON.parse(fs.readFileSync(DATA,'utf8'))}catch{return {}}};
const save=x=>fs.writeFileSync(DATA,JSON.stringify(x,null,2));
const token=()=>crypto.randomBytes(18).toString('base64url');
function allowed(raw){try{const u=new URL(raw);return u.protocol==='https:'&&(!ALLOWED_HOST||u.hostname===ALLOWED_HOST)}catch{return false}}
function extract(html){const marker='window.__SUB_PAGE_DATA__=',s=html.indexOf(marker);if(s<0)throw Error('Subscription data not found');const a=html.indexOf('{',s+marker.length);if(a<0)throw Error('Invalid subscription data');let d=0,q=null,e=false;for(let i=a;i<html.length;i++){const c=html[i];if(q){if(e)e=false;else if(c==='\\')e=true;else if(c===q)q=null;continue}if(c==='"'||c==="'"){q=c;continue}if(c==='{')d++;if(c==='}'){d--;if(d===0)return JSON.parse(html.slice(a,i+1))}}throw Error('Could not parse subscription data')}
async function fetchSub(url){if(!allowed(url))throw Error('Invalid or blocked subscription URL');const ac=new AbortController(),t=setTimeout(()=>ac.abort(),10000);try{const r=await fetch(url,{signal:ac.signal,headers:{'User-Agent':'DYNEX-Status/1.0'}});if(!r.ok)throw Error('Subscription server returned '+r.status);return extract(await r.text())}finally{clearTimeout(t)}}
app.post('/api/admin/create',(req,res)=>{if(!ADMIN_KEY||req.get('x-admin-key')!==ADMIN_KEY)return res.status(401).json({error:'Unauthorized'});const {customerName,subscriptionUrl}=req.body||{};if(!customerName||!subscriptionUrl)return res.status(400).json({error:'Customer name and subscription URL are required'});if(!allowed(subscriptionUrl))return res.status(400).json({error:'Use a valid HTTPS URL and set ALLOWED_HOST.'});const db=load(),t=token();db[t]={name:String(customerName).trim().slice(0,80),subscriptionUrl:String(subscriptionUrl).trim(),createdAt:new Date().toISOString()};save(db);res.json({ok:true,statusPath:'/status/'+t})});
app.get('/api/status/:token',async(req,res)=>{const c=load()[req.params.token];if(!c)return res.status(404).json({error:'Status link not found'});try{const d=await fetchSub(c.subscriptionUrl);res.set('Cache-Control','no-store').json({customerName:c.name,used:d.used??null,total:d.total??null,remained:d.remained??null,expire:d.expire??null,enabled:Boolean(d.enabled),isOnline:Boolean(d.isOnline),updatedAt:new Date().toISOString()})}catch(e){res.status(502).json({error:'Could not read live subscription status',detail:e.message})}});
app.get('/status/:token',(req,res)=>res.sendFile(path.join(__dirname,'public','status.html')));app.get('/health',(req,res)=>res.json({ok:true,service:'DYNEX STATUS'}));
app.listen(PORT,()=>console.log('DYNEX STATUS running on http://localhost:'+PORT));
